// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example: ```dart import 'firebase_options.dart'; // ...
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Y-vbiG7i4w-eFOnzwiCcBV9UuJDMcPo',
    appId: '1:569237066208:android:44ba8b8d0a2033e7391b85',
    messagingSenderId: '569237066208',
    projectId: 'matchup-cs734',
    databaseURL:
        'https://matchup-cs734-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matchup-cs734.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFxTy_fOBOnv8HCNb9LqBw5g6IyXz7UaU',
    appId: '1:569237066208:ios:03556224a09976ce391b85',
    messagingSenderId: '569237066208',
    projectId: 'matchup-cs734',
    databaseURL:
        'https://matchup-cs734-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matchup-cs734.firebasestorage.app',
    androidClientId:
        '569237066208-90gdlgssk4ga1pltfqs227f4qqbl3s37.apps.googleusercontent.com',
    iosClientId:
        '569237066208-92h5la0bv0df6nhnf7rl8bnn8djvpqdd.apps.googleusercontent.com',
    iosBundleId: 'nz.ac.auckland.matchup.matchupMobile',
  );
}
